title: Kleo Petrov's Magic Place
markdown: kramdown
permalink: pretty
exclude: [gulpfile.js, node_modules, assets/_scss]

highlighter: rouge

background: header-bg.jpg

less_than_minute: 1

gems: [jekyll-paginate]
paginate: 7
paginate_path: "page:num"
