title: Kleo Petrov - Front-End Developer
markdown: kramdown
permalink: pretty
exclude: [gulpfile.js, node_modules, assets/_scss]

highlighter: rouge

background: header-bg.jpg

paginate: 5

less_than_minute: 1
