---
title: Kleo Petrov's Magic Place
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
permalink: pretty
exclude:
- gulpfile.js
- node_modules
- assets/_scss
highlighter: rouge
background: header-bg.jpg
less_than_minute: 1
plugins:
- jekyll-paginate
paginate: 15
paginate_path: page:num
disqus:
  shortname: kleopetroff

